### ISSUE TITLE
POST requests fail

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/backend#67]
See https://github.com/datenanfragen/website/issues/1060 and https://github.com/datenanfragen/website/issues/1062.

**Comment by baltpeter** [comment]
A POST request causes the following error, which crashes the server (in prod, it is then automatically restarted by pm2):

```
An unhandled promise rejection occurred: TypeError: Cannot read properties of null (reading 'statusCode')
    at Request._finalize (/home/benni/coding/git-repos/Datenanfragen.de/backend/node_modules/@hapi/hapi/lib/request.js:491:31)
    at Request._reply (/home/benni/coding/git-repos/Datenanfragen.de/backend/node_modules/@hapi/hapi/lib/request.js:428:18)
    at Request._execute (/home/benni/coding/git-repos/Datenanfragen.de/backend/node_modules/@hapi/hapi/lib/request.js:274:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by baltpeter** [comment]
Unless I'm missing something, this isn't a problem in our code (the stack trace is entirely in `node_modules` and our code doesn't contain `statusCode` anywhere). And since this used to work, I guess the best course of action is to try and update hapi and the associated libraries in the hope that whatever the problem is was fixed upstream.

**Comment by baltpeter** [comment]
Updating hapi has solved the problem locally. Not much in the way of breaking changes, either. Only had to change imports from `@hapi/joi` to `joi`.

While I'm at it, I'll also update everything else.
